package Tokens;

public enum TokenType {
    UNKNOWN, VAR_DECL, CONST_DECL,
    TYPE_ID, ID, INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL,
    ADD, SUB, MULT, DIV, MOD,
    BITWISE_NOT, BITWISE_AND, BITWISE_OR,
    LOGICAL_NOT, LOGICAL_AND, LOGICAL_OR,
    GREATER, LESS, EQ, NOT_EQ, GEQ, LEQ,
    LPAREN, RPAREN, COLON, SEMICOLON, DOT, ASSIGNMENT,
    EOF
}
