package Tokens;

public enum TokenType {
    UNKNOWN, MUTABLE_VAR_DECL, IMMUTABLE_VAR_DECL,
    INT_TYPE_ID, FLOAT_TYPE_ID, BOOL_TYPE_ID,
    ID, INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL,
    BOOL_TRUE, BOOL_FALSE,
    PLUS, MINUS, ADD, SUB, MULT, DIV, MOD, POW,
    BITWISE_NOT, BITWISE_AND, BITWISE_OR,
    LOGICAL_NOT, LOGICAL_AND, LOGICAL_OR,
    GREATER, LESS, EQ, NOT_EQ, GEQ, LEQ,
    LPAREN, RPAREN, COLON, SEMICOLON, DOT, ASSIGNMENT,
    EOF
}
